### ISSUE TITLE
Browser error

### ISSUE THREAD

**Issue by ghost** [photopea/Typr.js#10]
Including the Typr.js script gives this error in Firefox

`unreachable code after return statement   Typr.js:86:2`

The relevant code
```
	{
		var num = Typr._bin.readShort(data, o);
		return num / 16384;
		
		var intg = (num >> 14), frac = ((num & 0x3fff)/(0x3fff+1));
		return (intg>0) ? (intg+frac) : (intg-frac);
	},
```

**Comment by photopea** [comment]
Hi, it is not an Error, it is just a **Warning** . We are aware of this part of the code. I am sure you can hide warnings in Firefox settings.
