### ISSUE TITLE
How to get baseline / x-height?

### ISSUE THREAD

**Issue by ghost** [photopea/Typr.js#12]
How did you calculate the baseline of the path?

I noticed the demo page and readme have the baseline marked, but I can't work out how to get the baseline of a path from the `font.hhea.ascender` and `font.hhea.descender` provided.

**Comment by photopea** [comment]
You define the baseline wherever you want. In font coordinates, the baseline has the Y=0.  The ascender is the height of the character above the baseline.

**Comment by ghost** [comment]
![img](https://user-images.githubusercontent.com/24791326/27955146-bb649ea8-6356-11e7-9e2d-ea2e0a4e6300.png)

Thanks @photopea. Also, how can I find the `x-height` of a path from Typr.js?

**Comment by photopea** [comment]
You are welcome. First of all, don't "find" anything from a path, i.e. never analyze vector curves to get any information about the font.
I think that the value that you are looking for is the sxHeight parameter of the OS/2 table:
https://www.microsoft.com/typography/otspec/os2.htm

**Comment by ghost** [comment]
Thanks. sxHeight is what I was looking for
