### ISSUE TITLE
Missing glyphs (.notdef)

### ISSUE THREAD

**Issue by guillem-catala** [photopea/Typr.js#15]
Hi I love this library!
I have a question, is there any way to know if a glyph is missing? Some fonts have chars that are not  designed and are usually represented by an square or empty space.

**Comment by photopea** [comment]
There is an agreement, that when some glyph is not defined, the font should map it to the glyph zero (which is usually a square).

So you can call Typr.U.codeToGlyph(font, charCode), and if it returns zero, the glyph is missing.
