### ISSUE TITLE
Doesn't support Unicode font. 

### ISSUE THREAD

**Issue by rothanachoun** [photopea/Typr.js#2]

**Comment by photopea** [comment]
Hi, what do you mean by Unicode font?

**Comment by rothanachoun** [comment]
<img width="866" alt="screen shot 2016-08-17 at 8 24 09 am" src="https://cloud.githubusercontent.com/assets/5331630/17721415/31349e56-6454-11e6-9cde-5c20faef0b34.png">

@photopea it display wrong result of Khmer Unicode font, but in fact it's because of displaying on Canvas. Anyways great thanks for this useful library.

**Comment by photopea** [comment]
Can you please share your font with me? I will take a look at it. Typr does not support all different glyph adjustments yet, but I would like to improve it.

**Comment by rothanachoun** [comment]
here it is
http://www.selapa.net/khmerfonts/fontinfo.php?font=1352
