### ISSUE TITLE
Generated fonts are of different sizes

### ISSUE THREAD

**Issue by vinaydotblog** [photopea/Typr.js#22]
I ran all my font collection through Typr.js to generate path of given font and text. Generated path are of different different sizes. As show in the screenshot below.

![image 1](https://user-images.githubusercontent.com/1058598/46788541-f325f500-cd57-11e8-89eb-3e3a9f24b520.png)
On left i have plain text and on right side an SVG element with <path> tag in it.

Can suggest any way to bring consistency to the generated path ? So that all spits out similar sizes paths. Thanks in advance. :)

**Comment by photopea** [comment]
Hey!  How exactly did you generate the vector paths?

When you call Typr.U.glyphsToPath(), it returns the path with integer coordinates, you have to scale them down. Did you take the font.head.unitsPerEm property into account?

**Comment by vinaydotblog** [comment]
Thanks for the quick reply. I did not consider unitsPerEm, it got fixed after considering it.
