### ISSUE TITLE
How to use typr.js to modify my glyph and use it back as a font ?

### ISSUE THREAD

**Issue by nestarz** [photopea/Typr.js#24]
Hello,

I want to modify each glyph of my font inside the browser (make it variable using mousePosition for example) and render it as a font (selectable, apply text-decoration, and everything), is it possible with Typr.js and if not, can I make it work with this lib and other ones ?

Thanks,

**Comment by photopea** [comment]
Hi, you can render text using Typr.js (see the description at the main page). But you can not save the new font into a TTF or OTF file.
