### ISSUE TITLE
Demo rendering position not correct on Hi-DPR screen

### ISSUE THREAD

**Issue by Axure** [photopea/Typr.js#32]
Incorrect:
<img width="915" alt="屏幕快照 2019-10-30 下午9 19 30" src="https://user-images.githubusercontent.com/3424317/67861350-02dacc00-fb5b-11e9-894d-d838511c3499.png">

Correct:
![屏幕快照 2019-10-30 下午9 20 21](https://user-images.githubusercontent.com/3424317/67861396-1dad4080-fb5b-11e9-91ee-6fd8e7adaebd.png)

**Comment by photopea** [comment]
Hi, I am afraid I don't understand :(

**Comment by yisibl** [comment]
![image](https://user-images.githubusercontent.com/2784308/78881461-6f9eae80-7a89-11ea-808e-33780aadbce2.png)
I also found a similar problem, the top of the character was cropped.

**Comment by photopea** [comment]
I understand now :) it is fixed!
