### ISSUE TITLE
support full GSUB and GPOS

### ISSUE THREAD

**Issue by be5invis** [photopea/Typr.js#4]

**Comment by photopea** [comment]
There already is some implementation of GPOS in sources, but it is not inserted into main library. Do you think you can test it and maybe implement GSUB in the same manner?

**Comment by be5invis** [comment]
the language, script, feature and lookup part are same between GSUB and GPOS. The only difference lies in the subtable level.

**Comment by photopea** [comment]
I have implemented the basic support for GSUB and GPOS. It is enough GSUB to render arabic text or to do ligatures. Is it sufficient for your problem?
