### ISSUE TITLE
support this font？

### ISSUE THREAD

**Issue by DLTech21** [photopea/Typr.js#40]
[font_13_13.zip](https://github.com/photopea/Typr.js/files/7386865/font_13_13.zip)
can fix to support this font type？？？ Thankyou！！！！

**Comment by photopea** [comment]
Hi, are you able to use that font file in any program at all? I need a proof, that it is a font file, and not e.g. an mp3 file renamed to .otf

**Comment by DLTech21** [comment]
use FontForge can open this font file
![image](https://user-images.githubusercontent.com/2238211/139093964-24057eb1-f1a2-437f-bf5a-c0dcb1e9b6be.png)

**Comment by photopea** [comment]
I could not install your font into Windows fonts, or use it e.g. in any text editor :(

**Comment by DLTech21** [comment]
you can install this software FontForge (https://fontforge.org/en-US/) 
it can see all the glyph

**Comment by DLTech21** [comment]
while using freetype to parse this font and get path from glyph ,  it comes

https://user-images.githubusercontent.com/2238211/139195678-b0516c84-0acd-46ea-b7a0-07b80bc73dfd.mp4

**Comment by photopea** [comment]
Can you convert your font into an OpenType font? So that it can be used e.g. in MS Word? Typr.js supports only OpenType fonts.

**Comment by DLTech21** [comment]
I solved by wasm based from  Freetype
