### ISSUE TITLE
Monaco.ttf from macOS

### ISSUE THREAD

**Issue by forresto** [photopea/Typr.js#42]
When I load Monaco.ttf in Typr, I get the error 

> Uncaught multiple tables for one platform+encoding

The font: [Monaco.ttf.zip](https://github.com/photopea/Typr.js/files/9450913/Monaco.ttf.zip)

<img width="397" alt="image" src="https://user-images.githubusercontent.com/395307/187381920-e050acc6-e8c1-4135-b8d1-aa2f09133981.png">

**Comment by forresto** [comment]
FWIW, that's the only macOS built-in that we have found that doesn't parse.

**Comment by photopea** [comment]
I just uploaded the latest Typr.js from my computer. Your font seems to work well in it.
