### ISSUE TITLE
 can add support for WOFF2 

### ISSUE THREAD

**Issue by zhang65681109** [photopea/Typr.js#44]
WOFF2 is now at Candidate Recommendation stage and is widely supported by the most popular browsers

**Comment by photopea** [comment]
I think the WOFF2 is just a wrapper around OTF, where the OTF tables are compressed with the Brotli algorithm.

It would require including the Brotli decompressor to Typr.js, which might be even larger than the Typr.js itself, so it will get quite messy.

I would rather not implement it. I am sure everyone who provides a WOFF2 font also provides the OTF version of that font, too.

**Comment by dhowe** [comment]
Any further thought on this? would be useful especially for google fonts users where this is often the default

**Comment by photopea** [comment]
I need a Brotli decompressor in Javascript, to be able to implement WOFF2. It would take me weeks to study and implement Brotli decompression, so it is not worth it for me :(

**Comment by dhowe** [comment]
what about using something like this: https://www.npmjs.com/package/brotli ?
looks like about 900k unminimised

**Comment by photopea** [comment]
I don't understand their source code. If you do, could you send me a JS function which decompresses binary data?

**Comment by herrstrietzel** [comment]
You can decompress woff2 files with the WASM build of wawoff2  
(The same approach currently used in opentype.js:)
``` 
<script src="https://unpkg.com/wawoff2@2.0.1/build/decompress_binding.js"></script>
```

When a font URL is referencing woff2 file you decompress the buffer before parsing it to a font object:  

```
async function loadFont(fontUrl) {
  // load font as a buffer
  let buffer = await (await fetch(fontUrl)).arrayBuffer();

  // check font file extension
  let ext = fontUrl.split(".").slice(-1)[0];

  // decompress buffer for woff2
  if (ext === "woff2") {
    buffer = Uint8Array.from(Module.decompress(buffer)).buffer;
  }

  // ready to parse font
  let font = Typr.parse(buffer)[0];
  return font;
}
```

See working [codepen demo](https://codepen.io/herrstrietzel/pen/VYZBKqP?editors=1010)
