### ISSUE TITLE
can support color font?

### ISSUE THREAD

**Issue by sunwanxin213** [photopea/Typr.js#45]
[NotoColorEmoji-Regular.zip](https://github.com/photopea/Typr.js/files/10558323/NotoColorEmoji-Regular.zip)

**Comment by photopea** [comment]
Our library Typr.js represents paths as vector shapes filled with a solid color. We can not represent gradients etc.

I have improved the support for your font, it should work better. But the gradients are ignored.

**Comment by sunwanxin213** [comment]
thanks!
