### ISSUE TITLE
Devanagri script/Hindi language ligatures not rendering correctly

### ISSUE THREAD

**Issue by CATALYST1109** [photopea/Typr.js#48]
Hi! I tried rendering Devanagri ligatures on the demo page and noticed that they are not rendering correctly as shown below.
I used the fonts Noto Sans and Mangal Regular, which do support that script. Is this something that typr doesn't support at the moment( I noticed GSUB and GPOS were commented out in [typr's code](https://github.com/photopea/Typr.js/blob/gh-pages/src/Typr.js) on lines 27 and 28) or am I just doing something wrong?

Context behind me pointing out GSUB and GPOS -- [jspdf issue](https://github.com/parallax/jsPDF/issues/2778#issuecomment-1639986258). I came here looking for a library that is able to handle such ligatures, to see if I can somehow port jspdf to use that instead of its own implementation, so I thought I'd inquire about the issue in hopes that it's an user error.

Thanks!

![typr](https://github.com/photopea/Typr.js/assets/25906573/3ef4d664-42ea-4fea-b82e-0b5d628853e4)

**Comment by photopea** [comment]
Hi, sadly, Typr.js does not have any advanced shaping capabilities. I recommend using the Harfbuzz library for shaping, see https://github.com/photopea/Typr.js#shaping-with-harfbuzz

**Comment by CATALYST1109** [comment]
Ok, thanks for your time !
