### ISSUE TITLE
Applying different colors to a single line of text.

### ISSUE THREAD

**Issue by xmejsieoke** [photopea/Typr.js#52]
I want to change the first three characters to white and the last three characters to red, but all characters are ending up with the final color.
![image](https://github.com/user-attachments/assets/57fbf173-0cf0-4485-b45a-8d68ff4440d0)
![image](https://github.com/user-attachments/assets/7c71d88b-eb5f-4b11-a313-23ccc0154b76)

**Comment by photopea** [comment]
try to call ctx.beginPath() before calling stringToContext()

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/beginPath

BTW. the latest Typr.js does not have stringToContext. I recommend switching to the latest Typr.js

**Comment by xmejsieoke** [comment]
Cool！
