### ISSUE TITLE
Font fallback handling.

### ISSUE THREAD

**Issue by xmejsieoke** [photopea/Typr.js#53]
I have subsetted a font, and when a corresponding character is not in the buffer, it does not render. ctx.fillText can display a default character for missing glyphs.
For example, my subsetted font does not include the '！' character.  
Typr render:
![image](https://github.com/user-attachments/assets/45bb586d-3fcb-43ea-a46e-41e1a42aaa45)
ctx.fillText: 
![image](https://github.com/user-attachments/assets/22a1ea55-c4c3-49d1-924a-be173f590bd7)
 Does Typr.js have a similar fallback mechanism?

**Comment by photopea** [comment]
When a glyph is not present in a font, shaping returns a glyph index zero. You can draw anything you want instead of these glyphs :)
