### ISSUE TITLE
Enhancement: provide font axes/style for variable fonts

### ISSUE THREAD

**Issue by dhowe** [photopea/Typr.js#56]
Using opentype.js one can access font variations axes and font styles for variable fonts in `tables.fvar.axes` and `tables.fvar.instances` respectively. Would be great if there was a way typr could do similar... ?

**Comment by dhowe** [comment]
Any update on this? thanks !

**Comment by photopea** [comment]
Hi, I have implemented the support for variable fonts, see https://github.com/photopea/Typr.js . It is also present in www.Photopea.com
