### ISSUE TITLE
Feature: load woff fonts

### ISSUE THREAD

**Issue by adriaanmeuris** [photopea/Typr.js#7]
I'm working on the multiline feature (https://github.com/photopea/Typr.js/issues/6), but I was wondering if there's any chance of parsing woff-fonts.

If not, is it an idea to use the woff-parsing of opentype, or would I lose better font support like stated in https://github.com/nodebox/opentype.js/issues/214?

**Comment by photopea** [comment]
A Woff file is just a zipped OTF file.  After you unzip it, you can use Typr.js to work with that file.

I am afraid that if I add unzipping algorithms into Typr.js, it may become four times larger.

**Comment by adriaanmeuris** [comment]
No problem, just looking into how I could parse it myself. Would https://github.com/andyjansson/woff-parser be a good start?

**Comment by photopea** [comment]
That library looks like it needs Node.js environment, I am not sure if you can run it at client side.

I would look into WOFF file specification first, then unzipped it with a ZIP library to get a OTF file.

**Comment by adriaanmeuris** [comment]
alright, thanks for your tips!

**Comment by dhowe** [comment]
Any solution on this one @adriaanmeuris ? Looking to do the same here...

**Comment by photopea** [comment]
I have already implemented the support for WOFF into Typr.js, it will be published here on github within the next two weeks.

**Comment by dhowe** [comment]
great news -- looking forward to it

**Comment by dhowe** [comment]
can we re-open this, so that we can track when its ready ?

**Comment by photopea** [comment]
WOFF fonts are supported by the latest release of Typr.js. Just give it a WOFF file as if it was a TTF file.  It requires pako.js for Deflate decompression. It supports only WOFF and not WOFF2.

**Comment by dhowe** [comment]
see #57
