### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by ghost** [photopea/Typr.js#9]
Can you add this library to NPM.

**Comment by photopea** [comment]
We think that the current way of how NPM works is quite complex. We would like to discuss a possible improvement, when the code would be stored just at one place and other services would be able to use it from there.  You can join the discussion here: https://github.com/npm/www/issues/173

**Comment by dhowe** [comment]
Greetings. We briefly discussed an npm package in email - is this something you are interested in having in the typr repo, or should I create one in a separate (forked) repo  ? thanks

**Comment by photopea** [comment]
I never used NPM, so I am not the best person to make npm packages, I think.

**Comment by awa-xima** [comment]
For reference, I made [a fork with NPM + TypeScript support](https://github.com/blutorange/Typr.js):

Btw, now that we have ESM (EcmaScript modules), making a package is now way easier compared with what you tried in the `feature/npm` / `feature/package` branches. All you need to do is to add a single `export` statement to the JS files; and a package.json with some meta data regarding your package.

```
npm add @xenorange/typr.js
yarn add @xenorange/typr.js
```
